@Presentation_HostAddress = http://localhost:8081
@BearerToken = 

###

POST {{Presentation_HostAddress}}/Security/Accounts/Login
Content-Type: application/json
Accept: application/json

{
  "username": "admin",
  "password": "admin"
}

###

POST {{Presentation_HostAddress}}/Security/Accounts/Register
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{BearerToken}}

{
  "username": "jdoe",
  "password": "P@ssw0rd123!",
  "email": "noemail@noemail.com",
  "firstName": "John",
  "lastName": "Doe"
}

###

POST {{Presentation_HostAddress}}/Security/Users/AssignRoleToUser
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{BearerToken}}

{
  "username": "jdoe",
  "roleName": "User"
}

###

GET {{Presentation_HostAddress}}/Security/Users/Profiles/SearchProfileByName?Name=N
Content-Type: application/json
Authorization: Bearer {{BearerToken}}

###

GET {{Presentation_HostAddress}}/Security/Users/Profiles/e45acefa-74b0-4f28-b81f-fbc02d9778b5
Content-Type: application/json
Authorization: Bearer {{BearerToken}}

###

POST {{Presentation_HostAddress}}/Issues
Content-Type: application/json
Application-Json: application/json
Authorization: Bearer {{BearerToken}}

{
  "name": "Request timed out",
  "reporterid": "E45ACEFA-74B0-4F28-B81F-FBC02D9778B5"
}

###

GET {{Presentation_HostAddress}}/Issues/SXP-1
Content-Type: application/json
Authorization: Bearer {{BearerToken}}

###

GET {{Presentation_HostAddress}}/Issues
Content-Type: application/json
Authorization: Bearer {{BearerToken}}

###

PUT {{Presentation_HostAddress}}/Issues/SXP-1
Content-Type: application/json
Application-Json: application/json
Authorization: Bearer {{BearerToken}}

{
  "name": "Request timed out - Updated",
  "issuestatusid": "1",
  "issuepriorityid": "3",
  "reporterid": "E45ACEFA-74B0-4F28-B81F-FBC02D9778B5"
}

###

POST {{Presentation_HostAddress}}/Issues/SXP-1/Comments
Content-Type: application/json
Application-Json: application/json
Authorization: Bearer {{BearerToken}}

{
  "content": "This is a comment"
}

###

GET {{Presentation_HostAddress}}/Issues/SXP-1/Comments
Content-Type: application/json
Authorization: Bearer {{BearerToken}}

###