@Presentation_HostAddress = https://localhost:7090/api

###
GET {{Presentation_HostAddress}}/issues/
Accept: application/json

###
GET {{Presentation_HostAddress}}/issues/SXP-1?includeComments=True/
Accept: application/json

###
POST {{Presentation_HostAddress}}/issues/
Accept: application/json
Content-Type: application/json
{
 "name": "Request timed out",
 "description": "Time out error on page load.",
 "issuePriorityId": 3
}

###
PUT {{Presentation_HostAddress}}/issues/SXP-1/
Accept: application/json
Content-Type: application/json
{
  "name": "Request timed out - Updated",
  "description": "Time out error on page load.",
  "issuePriorityId": 3,
  "issueStatusId": 1
}

### Assuming there is an issue with 1 as its Id
GET {{Presentation_HostAddress}}/issues/SXP-1/comments/
Accept: application/json

###
POST {{Presentation_HostAddress}}/issues/SXP-1/comments/
Accept: application/json
Content-Type: application/json

{
  "content": "Lorem ipsum dolor sit amet",
  "issueKey": "SXP-1"
}

###